Made fortress script smarter about auto-homing

diff --git a/ProjectFortress/fortress b/ProjectFortress/fortress
--- a/ProjectFortress/fortress
+++ b/ProjectFortress/fortress
@@ -17,12 +17,37 @@
 #    trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 ################################################################################
 
-echo $FORTRESS_HOME
+
+if [ -z "$FORTRESS_HOME" ]; then
+  cmd=$0
+  emptyifslash=${cmd##*/*}
+  if [ -z "$emptyifslash" ]; then
+    # slash occurs in name, use as is
+    true;
+  else
+    # no slash
+    cmd=`which $cmd`
+  fi
+  if [ -L $cmd ]; then
+     echo "You need to set FORTRESS_HOME to the directory containing ProjectFortress"
+     echo "The target of the symbolic link could not be followed."
+     exit 1
+  fi
+  FORTRESS_HOME=${cmd%/*}/..
+  echo guessing FORTRESS_HOME=$FORTRESS_HOME
+fi
+
+if [ -e ${FORTRESS_HOME}/ProjectFortress ]; then
+  true
+else
+  echo "FORTRESS_HOME should be the name of the parent directory of ProjectFortress"
+  echo "instead of '$FORTRESS_HOME'"
+  exit 1
+fi
 
 if (uname | egrep -q CYGWIN) ; then 
   CP="build;third_party/junit/junit.jar;third_party/xtc/xtc.jar;third_party/jsr166y/jsr166y.jar;third_party/plt/plt.jar"
 else
-
   CP="$FORTRESS_HOME/ProjectFortress/build:$FORTRESS_HOME/ProjectFortress/third_party/junit/junit.jar:$FORTRESS_HOME/ProjectFortress/third_party/xtc/xtc.jar:$FORTRESS_HOME/ProjectFortress/third_party/jsr166y/jsr166y.jar:$FORTRESS_HOME/ProjectFortress/third_party/plt/plt.jar"
 fi
 
